# Generated by Django 4.0.5 on 2023-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facematching',
            name='match_percentage',
            field=models.FloatField(null=True),
        ),
    ]
