# Generated by Django 3.1.2 on 2023-06-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userselectedapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectedapi',
            name='api',
        ),
        migrations.AddField(
            model_name='userselectedapi',
            name='api',
            field=models.ManyToManyField(to='api.API'),
        ),
    ]
