# Generated by Django 3.1.2 on 2023-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230611_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectedapi',
            name='api',
            field=models.ManyToManyField(related_name='selected_apis', to='api.API'),
        ),
    ]
