# Generated by Django 4.0.5 on 2023-06-02 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquifaxAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_column='created_on', default=django.utils.timezone.localtime)),
                ('updated_on', models.DateTimeField(db_column='updated_on', default=django.utils.timezone.localtime)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('response_data', models.JSONField()),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
