# Generated by Django 4.0.5 on 2023-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equifaxApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equifaxapi',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='equifaxapi',
            name='user_id',
        ),
        migrations.AddField(
            model_name='equifaxapi',
            name='AddressLine1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equifaxapi',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equifaxapi',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equifaxapi',
            name='PanNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equifaxapi',
            name='Postal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equifaxapi',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
