# Generated by Django 3.1.2 on 2023-06-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquifaxAPI', '0003_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
