# Generated by Django 3.1.2 on 2023-06-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquifaxAPI', '0002_auto_20230611_0223'),
        ('EquifaxAPI', '0004_delete_notes'),
    ]

    operations = [
    ]
