# Generated by Django 3.1.2 on 2023-07-03 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_column='created_on', default=django.utils.timezone.localtime)),
                ('updated_on', models.DateTimeField(db_column='updated_on', default=django.utils.timezone.localtime)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pan_number', models.CharField(max_length=10)),
                ('response_data', jsonfield.fields.JSONField(null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OtpVerificationAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_column='created_on', default=django.utils.timezone.localtime)),
                ('updated_on', models.DateTimeField(db_column='updated_on', default=django.utils.timezone.localtime)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client_id', models.CharField(max_length=200)),
                ('otp', models.IntegerField(max_length=6)),
                ('response_data', jsonfield.fields.JSONField(null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AadhaarAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_column='created_on', default=django.utils.timezone.localtime)),
                ('updated_on', models.DateTimeField(db_column='updated_on', default=django.utils.timezone.localtime)),
                ('is_deleted', models.BooleanField(default=False)),
                ('aadhaar_number', models.BigIntegerField(max_length=12)),
                ('response_data', jsonfield.fields.JSONField(null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
